repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.11"
    hooks:
      - id: ruff # ~flake8 + isort
        types_or: [python, pyi]
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format # ~black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        types_or: [yaml, markdown]
