defaults:
  - data: default
  - model: roberta-base
  - training: default
  - logging: mlflow
  - export: default

project_name: "generated_text_detection"
seed: 42

models_dir: "models"
onnx_models_dir: "${models_dir}/onnx"
tensorrt_models_dir: "${models_dir}/tensorrt"

dir: "outputs/${model.name}"

hydra:
  run:
    dir: ${dir}
  output_subdir: .hydra
  job:
    chdir: True
